import streamlit as st
st.set_page_config(page_title="MICO-JDEQ Digital Twin", layout="wide")
st.title("🌐 MICO-JDEQ Digital Awareness OS")
cols = st.columns(4)
cols[0].metric("Scout (Vivo Y28)", "🟢 ONLINE", "Komandan")
cols[1].metric("Radar (Z83)", "🟢 ONLINE", "Gateway")
cols[2].metric("Penjaga (Infinix)", "🟢 ONLINE", "Sensor")
cols[3].metric("PC i5", "🔴 OFFLINE", "Menunggu SATA")
st.header("📡 Infrastruktur")
st.write("- **Git:** 62 commits, GitHub + HuggingFace")
st.write("- **State:** 6 tabel, state-driven architecture")
st.write("- **Keamanan:** DOLA Gatekeeper, 37 pola XSS, Kill-Switch")
st.write("- **Cloud:** 8 workers (Groq, GCloud, Colab, Drive, Telegram, ThingsBoard)")
st.header("🤖 Agen AI")
st.write("13 agen terdaftar: Groq, DeepSeek, Gemini, ChatGPT, Claude, Perplexity, dll")
st.caption("© 2026 MICO-JDEQ Awareness Digital — Iswan Juman Pancoro, ST")
