#!/usr/bin/env bash
clear
echo -e "\033[0;34m============================================\033[0m"
echo -e "\033[0;32m   PANDUAN AKTIFASI SHIZUKU (Vivo Y28)\033[0m"
echo -e "\033[0;34m============================================\033[0m"
echo ""
echo "Cara iki TANPA KOMPUTER, cukup HP tok."
echo "Sawisé Shizuku urip, MICO JDEQ bakal isa resik cache otomatis."
echo ""
echo "LANGKAH-LANGKAH:"
echo "1. Bukak aplikasi 'Setelan' (Settings)."
echo "2. Gulung mangisor, bukak 'Tentang ponsel'."
echo "3. Tap 'Versi perangkat lunak' ping 7x nganti metu 'Opsi pangembang'."
echo "4. Bali menyang Setelan > 'Sistem' (utawa 'Setelan tambahan') > 'Opsi pangembang'."
echo "5. Aktifké 'USB debugging' LAN 'Wireless debugging'."
echo "6. Bukak aplikasi Shizuku."
echo "7. Pilih 'Start via wireless debugging'."
echo "8. Pilih 'Pairing' (mung sapisan)."
echo "9. Balik menyang Setelan > Opsi pangembang > Wireless debugging."
echo "10. Tap 'Pasangake piranti nganggo kode pasangan'."
echo "11. Kode 6 digit bakal muncul. Lebokné ing notifikasi Shizuku."
echo "12. Sawisé pairing sukses, balik menyang Shizuku, pilih 'Start'."
echo "13. Yen Shizuku statusé 'Running', MATUR NUWUN, rampung!"
echo ""
echo "Yen gagal, mateni lan uripaké manèh Wireless debugging."
echo "Sawisé iku, bukak Termux lan jalanaké manèh skrip MICO:"
echo "  bash /sdcard/mico_ultimate.sh"
echo ""
